# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Emma Redor
description: >- # this means to ignore newlines until "baseurl:"
  Emma Redor's website.
baseurl: "" # the subpath of the site
url: "https://emmaredor.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    #- name: Work
    #- name: Blog
    - name: CV

footer:
  show_powered_by: false
  contact:
    - type: email
      name: Email
      value: emma.redor@ens-rennes.fr
  follow:
    - type: github
      name: GitHub
      link: http://github.com/emmaredor

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
